version: "3.5"
services:
  etherpad:
    image: elestio/etherpad:${SOFTWARE_VERSION_TAG}
    container_name: etherpad
    restart: always
    hostname: etherpad
    environment:
      DB_TYPE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: etherpad
      DB_USER: postgres
      DB_PASS: ${ADMIN_PASSWORD}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      TRUST_PROXY: "true"
      COMMIT_RATE_LIMIT_DURATION: 1000000
      COMMIT_RATE_LIMIT_POINTS: 1000000
      IMPORT_EXPORT_MAX_REQ_PER_IP: 1000000
      IMPORT_EXPORT_RATE_LIMIT_WINDOW: 9000000
    ports:
      - "172.17.0.1:9001:9001"
    depends_on:
      - postgres  

  postgres:
    restart: always
    image: elestio/postgres:15
    container_name: postgres
    environment:
      - POSTGRES_DB=etherpad
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 172.17.0.1:53649:5432

  pgadmin4:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "172.17.0.1:29756:8080"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
